name: Run Tests
on: push
jobs:
  test:
    name: Run Test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: Dockerfile.ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "149915512+HSarao004@users.noreply.github.com"
          git config --global user.name "Hsarao2"

      - name: Build Docker image
        run: docker build -t main -f $COMPOSE_FILE .

      - name: Run tests
        run: docker run main
        

